SEEDED_CASES = [
    {
        "name": "Mild Case",
        "person_id": 1001,
        "gender": "Female",
        "age": 25,
        "occupation": "Student",
        "sleep_duration": 7.3,
        "sleep_quality": 8,
        "activity_level": 65,
        "stress_level": 4,
        "bmi_category": "Normal",
        "blood_pressure": "118/76",
        "heart_rate": 68,
        "daily_steps": 9000,
        "sleep_disorder": None,
    },
    {
        "name": "Moderate Case",
        "person_id": 1002,
        "gender": "Male",
        "age": 28,
        "occupation": "Software Engineer",
        "sleep_duration": 6.0,
        "sleep_quality": 6,
        "activity_level": 40,
        "stress_level": 7,
        "bmi_category": "Overweight",
        "blood_pressure": "126/83",
        "heart_rate": 77,
        "daily_steps": 4200,
        "sleep_disorder": None,
    },
    {
        "name": "Severe Case",
        "person_id": 1003,
        "gender": "Male",
        "age": 31,
        "occupation": "Doctor",
        "sleep_duration": 4.8,
        "sleep_quality": 4,
        "activity_level": 20,
        "stress_level": 8,
        "bmi_category": "Obese",
        "blood_pressure": "138/90",
        "heart_rate": 88,
        "daily_steps": 3000,
        "sleep_disorder": "Insomnia",
    },
]